"""
Extra Wikipedia titles for scaling EpiChat (disjoint focus: langs & infra missing elsewhere).

Titles must match English Wikipedia article names; seed_wikipedia skips missing pages.

Combined with scripts/generate_eus.py WIKI_TOPICS (~484), dedup is applied at runtime in scale_epichat_graph.py.
"""
from __future__ import annotations


def _languages_and_runtimes() -> list[str]:
    return [
        "Perl",
        "Ruby (programming language)",
        "PHP",
        "Scala (programming language)",
        "Haskell (programming language)",
        "OCaml",
        "Erlang (programming language)",
        "Elixir (programming language)",
        "Clojure",
        "Scheme (programming language)",
        "Common Lisp",
        "Prolog",
        "Fortran",
        "COBOL",
        "Pascal (programming language)",
        "Ada (programming language)",
        "Assembly language",
        "WebAssembly",
        "Rust (programming language)",
        "Swift (programming language)",
        "Dart (programming language)",
        "Lua (programming language)",
        "Groovy (programming language)",
        "Julia (programming language)",
        "R (programming language)",
        "MATLAB",
        "Objective-C",
        "Scratch (programming language)",
        "Visual Basic (.NET)",
        "F Sharp (programming language)",
        "Crystal (programming language)",
        "Nim (programming language)",
        "Zig (programming language)",
        "V (programming language)",
        "Carbon (programming language)",
        "Delphi (software)",
        "PowerShell",
        "Bash (Unix shell)",
        "Z shell",
        "Fish (Unix shell)",
        "Awk",
        "Sed",
        "Tcl",
        "Smalltalk",
        "Forth (programming language)",
        "APL (programming language)",
        "IBM RPG",
        "ABAP",
        "ActionScript",
        "ColdFusion Markup Language",
        "VBScript",
        "Transact-SQL",
        "PL/SQL",
        "OpenCL",
        "CUDA",
        "Metal (API)",
        "Vulkan (API)",
        "DirectX",
        "OpenGL",
        "WebGPU",
        "Shader",
        "Compute shader",
        "High-Level Shader Language",
        "OpenGL Shading Language",
        "Verilog",
        "VHDL",
        "SystemVerilog",
    ]


def _frameworks_web() -> list[str]:
    return [
        "Vue.js",
        "Svelte",
        "SvelteKit",
        "Ember.js",
        "Backbone.js",
        "Meteor (web framework)",
        "Alpine.js",
        "SolidJS",
        "Lit (library)",
        "Preact",
        "htmx",
        "Hotwire (software)",
        "Phoenix (web framework)",
        "Laravel",
        "Symfony",
        "CodeIgniter",
        "Ruby on Rails",
        "Sinatra (software)",
        "Hanami (web framework)",
        "Play Framework",
        "Apache Struts",
        "Dropwizard",
        "Micronaut (framework)",
        "Vert.x",
        "Ratpack",
        "Padrino (web framework)",
        "Camping (microframework)",
        "Seaside (software)",
        "FuelPHP",
        "CakePHP",
        "Yii",
        "Zend Framework",
        "Phalcon (framework)",
        "Fastify",
        "Hapi.js",
        "Koa (web framework)",
        "FeathersJS",
        "Socket.IO",
        "ws (protocol)",
        "GraphQL",
        "Apollo GraphQL",
        "Relay (JavaScript framework)",
        "OpenAPI Specification",
        "Swagger (software)",
        "JSON Schema",
        "Protocol Buffers",
        "Apache Avro",
        "Apache Thrift",
        "MessagePack",
        "Apache Kafka",
        "RabbitMQ",
        "Apache Pulsar",
        "Amazon Simple Queue Service",
        "Redis",
        "Memcached",
        "Celery (software)",
        "Sidekiq",
        "Apache Airflow",
        "Luigi (software)",
        "Prefect (software)",
        "dbt (software)",
        "Apache NiFi",
        "Talend",
        "Informatica",
        "Microsoft SSIS",
        "Apache Sqoop",
        "Apache Flume",
        "Logstash",
        "Fluentd",
        "Vector (software)",
        "OpenTelemetry",
        "Jaeger (software)",
        "Zipkin (software)",
        "Prometheus (software)",
        "Grafana",
        "Sentry (software)",
        "Rollbar",
        "Splunk",
        "Elasticsearch",
        "OpenSearch (software)",
        "Solr",
        "Meilisearch",
        "Typesense",
        "Algolia",
        "Amazon CloudFront",
        "Fastly",
        "Akamai",
        "Cloudflare",
        "Let's Encrypt",
        "Certbot",
        "HashiCorp Vault",
        "AWS Secrets Manager",
        "Open Policy Agent",
        "SPIFFE",
        "OAuth",
        "OpenID Connect",
        "JSON Web Token",
        "SAML",
        "Kerberos (protocol)",
        "LDAP",
        "Active Directory",
        "Security Assertion Markup Language",
        "WebAuthn",
        "FIDO Alliance",
        "Passkeys",
        "CAPTCHA",
        "reCAPTCHA",
        "Cloudflare Bot Management",
        "OWASP Top 10",
        "Application security",
        "Threat modeling",
        "STRIDE (security)",
        "Penetration test",
        "Red team",
        "Blue team (computer security)",
        "Security operations center",
        "Incident response",
        "Computer forensics",
        "Malware analysis",
        "Rootkit",
        "Bootkit",
        "Trojan horse (computing)",
        "Computer worm",
        "Computer virus",
        "Ransomware",
        "Spyware",
        "Adware",
        "Keylogger",
        "Botnet",
        "Command and control (malware)",
        "Living off the land",
        "Supply chain attack",
        "Zero-day (computing)",
        "CVE",
        "CVSS",
        "Common Weakness Enumeration",
        "Static application security testing",
        "Dynamic application security testing",
        "Interactive application security testing",
        "Software composition analysis",
        "Dependabot",
        "Renovate (software)",
        "SBOM",
        "Sigstore",
        "Cosign (software)",
        "Notary (software)",
        "The Update Framework",
        "Binary transparency",
        "Reproducible builds",
    ]


def _systems_os_kernel() -> list[str]:
    return [
        "Linux",
        "GNU",
        "Linux kernel",
        "System call",
        "ioctl",
        "cgroups",
        "Namespaces (Linux)",
        "Linux namespaces",
        "seccomp",
        "AppArmor",
        "SELinux",
        "Linux capabilities",
        "systemd",
        "init",
        "BusyBox",
        "Alpine Linux",
        "CentOS",
        "Rocky Linux",
        "AlmaLinux",
        "Red Hat Enterprise Linux",
        "Ubuntu",
        "Debian",
        "Fedora Linux",
        "Arch Linux",
        "NixOS",
        "Gentoo Linux",
        "FreeBSD",
        "OpenBSD",
        "NetBSD",
        "DragonFly BSD",
        "macOS",
        "Darwin (operating system)",
        "Windows NT",
        "Windows Subsystem for Linux",
        "Wine (software)",
        "Hyper-V",
        "KVM (hypervisor)",
        "Xen",
        "VMware ESXi",
        "VirtualBox",
        "QEMU",
        "Kubernetes",
        "Nomad (software)",
        "Apache Mesos",
        "Docker (software)",
        "Podman",
        "containerd",
        "CRI-O",
        "Open Container Initiative",
        "Helm (package manager)",
        "Kustomize",
        "Istio",
        "Linkerd",
        "Envoy (software)",
        "Contour (software)",
        "NGINX",
        "Apache HTTP Server",
        "Caddy (web server)",
        "Traefik Proxy",
        "HAProxy",
        "Varnish (software)",
        "Squid (software)",
        "Memcached",
        "Consul (software)",
        "etcd",
        "Apache ZooKeeper",
        "Raft (algorithm)",
        "Paxos (computer science)",
        "Cap theorem",
        "Byzantine fault",
        "Leader election",
        "Gossip protocol",
        "Vector clock",
        "Lamport timestamp",
        "Happened-before",
        "Linearizability",
        "Serializability",
        "Snapshot isolation",
        "Optimistic concurrency control",
        "Pessimistic locking",
        "Lost update",
        "Phantom row",
        "Write skew",
        "Read skew",
        "Clock skew",
        "Time synchronization",
        "Network Time Protocol",
        "Precision Time Protocol",
        "Leap second",
        "Real-time computing",
        "Hard real-time computing",
        "Rate-monotonic scheduling",
        "Earliest deadline first scheduling",
        "Completely fair scheduler",
        "Interrupt",
        "Polling (computer science)",
        "DMA attack",
        "Row hammer",
        "Spectre (security vulnerability)",
        "Meltdown (security vulnerability)",
        "Microarchitectural Data Sampling",
        "Return-oriented programming",
        "Control-flow integrity",
        "Stack canary",
        "Position-independent code",
        "RELRO",
        "Executable-space protection",
        "W^X",
        "Sandbox (computer security)",
        "Virtualization-based security",
        "Trusted Platform Module",
        "Unified Extensible Firmware Interface",
        "Secure Boot",
        "Measured boot",
        "Remote attestation",
        "Confidential computing",
        "Intel Software Guard Extensions",
        "AMD Secure Encrypted Virtualization",
        "Arm TrustZone",
    ]


def _languages_more_cs_theory() -> list[str]:
    return [
        "Abstract interpretation",
        "Abstract syntax tree",
        "Symbol table",
        "Intermediate representation",
        "Static single assignment form",
        "Control-flow graph",
        "Call graph",
        "Data-flow analysis",
        "Escape analysis",
        "Points-to analysis",
        "Alias analysis",
        "Live variable analysis",
        "Reaching definition",
        "Available expression",
        "Constant folding",
        "Constant propagation",
        "Dead code elimination",
        "Common subexpression elimination",
        "Loop invariant code motion",
        "Strength reduction",
        "Loop unrolling",
        "Loop fusion",
        "Loop fission",
        "Tail call",
        "Continuation-passing style",
        "Visitor pattern",
        "Recursive descent parser",
        "LL parser",
        "LR parser",
        "LALR parser",
        "Earley parser",
        "Packrat parser",
        "Parsing expression grammar",
        "Lexical analysis",
        "Regular language",
        "Context-free grammar",
        "Context-sensitive grammar",
        "Chomsky hierarchy",
        "Pushdown automaton",
        "Finite-state machine",
        "Turing machine",
        "Automata theory",
        "Computability theory",
        "Halting problem",
        "Rice's theorem",
        "Church–Turing thesis",
        "Lambda calculus",
        "Fixed-point combinator",
        "Currying",
        "Lazy evaluation",
        "Strict evaluation",
        "Thunk",
        "Continuation",
        "Coroutine",
        "Fibonacci heap",
        "Pairing heap",
        "Binomial heap",
        "Leftist tree",
        "Splay tree",
        "Treap",
        "Scapegoat tree",
        "Ternary search tree",
        "Radix tree",
        "Patricia trie",
        "Suffix automaton",
        "Aho–Corasick algorithm",
        "Knuth–Morris–Pratt algorithm",
        "Boyer–Moore string-search algorithm",
        "Rabin–Karp algorithm",
        "Rolling hash",
        "Consistent hashing",
        "Rendezvous hashing",
        "Chord (peer-to-peer)",
        "Pastry (DHT)",
        "Kademlia",
        "Distributed hash table",
        "Vector clock",
        "Mercury (logic programming)",
        "Datalog",
        "Answer set programming",
        "Constraint programming",
        "Integer programming",
        "Linear programming",
        "Simplex algorithm",
        "Interior-point method",
        "Convex optimization",
        "Gradient boosting",
        "XGBoost",
        "LightGBM",
        "CatBoost",
        "Random forest",
        "Extra Trees",
        "Isolation forest",
        "Permutation feature importance",
        "SHAP (machine learning)",
        "LIME (machine learning)",
        "Calibration (statistics)",
        "Platt scaling",
        "Isotonic regression",
        "Receiver operating characteristic",
        "Precision and recall",
        "F-score",
        "Confusion matrix",
        "Statistical significance",
        "P-value",
        "Confidence interval",
        "Bayesian inference",
        "Markov chain Monte Carlo",
        "Metropolis–Hastings algorithm",
        "Gibbs sampling",
        "Variational Bayesian methods",
        "Expectation–maximization algorithm",
        "Hidden Markov model",
        "Conditional random field",
        "Max-margin Markov networks",
        "Structured prediction",
        "Viterbi algorithm",
        "Beam search",
        "Greedy decoding",
        "Top-p sampling",
        "Temperature (machine learning)",
        "Mixture of experts",
        "Sparse mixture of experts",
        "Mixture model",
        "Gaussian mixture model",
        "Expectation maximization",
        "Kalman filter",
        "Particle filter",
        "Recursive Bayesian estimation",
        "Signal processing",
        "Nyquist–Shannon sampling theorem",
        "Discrete Fourier transform",
        "Fast Fourier transform",
        "Convolution",
        "Digital filter",
        "Finite impulse response",
        "Infinite impulse response",
        "Window function",
        "Spectrogram",
        "Mel-frequency cepstrum",
        "Wavelet transform",
        "Principal component analysis",
        "Independent component analysis",
        "Singular value decomposition",
        "Low-rank approximation",
        "Matrix factorization",
        "Non-negative matrix factorization",
        "Collaborative filtering",
        "Content-based filtering",
        "Learning to rank",
        "LambdaRank",
        "NDCG",
        "Mean reciprocal rank",
        "Mean average precision",
        "Information retrieval",
        "Okapi BM25",
        "TF-IDF",
        "Inverted index",
        "Posting list",
        "MinHash",
        "Locality-sensitive hashing",
        "SimHash",
        "Jaccard index",
        "Cosine similarity",
        "Euclidean distance",
        "Manhattan distance",
        "Chebyshev distance",
        "Mahalanobis distance",
        "Earth mover's distance",
        "Dynamic time warping",
        "Edit distance",
        "Levenshtein distance",
        "Hamming distance",
        "Needleman–Wunsch algorithm",
        "Smith–Waterman algorithm",
        "Sequence alignment",
        "Suffix tree",
        "Burrows–Wheeler transform",
        "Run-length encoding",
        "Huffman coding",
        "Arithmetic coding",
        "Lempel–Ziv–Welch",
        "DEFLATE",
        "Snappy (compression)",
        "LZ4 (compression algorithm)",
        "Zstandard",
        "Brotli",
        "JPEG",
        "PNG",
        "WebP",
        "AVIF",
        "HEIF",
        "Video coding format",
        "H.264/MPEG-4 AVC",
        "HEVC",
        "AV1",
        "VP9",
        "Opus (audio format)",
        "Vorbis",
        "AAC",
        "FLAC",
        "MP3",
        "Container format (digital)",
        "FFmpeg",
        "GStreamer",
        "WebRTC",
        "Real-time Transport Protocol",
        "Session Description Protocol",
        "Interactive Connectivity Establishment",
        "DTLS",
        "SRTP",
        "Stream Control Transmission Protocol",
    ]


def _list_and_comparison_articles() -> list[str]:
    lists = [
        "List of programming languages",
        "List of programming languages by type",
        "List of JVM languages",
        "List of Python software",
        "List of Python libraries",
        "List of Java APIs",
        "List of Java frameworks",
        "List of .NET libraries and frameworks",
        "List of JavaScript libraries",
        "List of PHP frameworks",
        "List of Ruby libraries",
        "List of Rust libraries",
        "List of Go software",
        "List of software forks",
        "List of open-source video games",
        "List of version-control software",
        "List of spreadsheet software",
        "List of computer algebra systems",
        "List of numerical-analysis software",
        "List of finite element software packages",
        "List of optimization software",
        "List of statistical packages",
        "List of geographic information systems software",
        "List of relational database management systems",
        "List of ACID-compliant database management systems",
        "List of XML schemas",
        "List of JSON datasets",
        "List of HTTP headers",
        "List of HTTP status codes",
        "List of TCP and UDP port numbers",
        "List of DNS record types",
        "List of Unix commands",
        "List of GNU Core Utilities commands",
        "List of TCP congestion control algorithms",
        "List of WLAN channels",
        "List of Linux distributions",
        "List of macOS components",
        "List of Microsoft Windows components",
        "List of Microsoft Visual Studio add-ins",
        "List of backup software",
        "List of antivirus software",
        "List of intrusion detection systems",
        "List of security hacking incidents",
        "List of data breaches",
        "List of ransomware cyberattacks",
        "List of common desktop resolutions",
        "List of file formats",
        "List of archive formats",
        "List of video codecs",
        "List of ISO standards",
        "List of IEC standards",
        "List of RFCs",
        "List of Internet top-level domains",
        "List of search engines",
        "List of web browsers",
        "List of web servers",
        "List of web service protocols",
        "List of instant messaging protocols",
        "List of collaborative software",
        "List of collaborative real-time editors",
        "List of issue-tracking systems",
        "List of project management software",
        "List of build automation software",
        "List of continuous integration tools",
        "List of configuration management tools",
        "List of container orchestration tools",
        "List of infrastructure as code software",
        "List of observability software",
        "List of network analyzers",
        "List of packet analyzers",
        "List of debugging tools",
        "List of performance analysis tools",
        "List of profiling tools",
        "List of memory debuggers",
        "List of tools for static analysis of software",
        "List of unit testing frameworks",
        "List of code coverage tools",
        "List of API testing tools",
        "List of load testing tools",
        "List of chaos engineering tools",
        "List of feature toggle systems",
        "List of job scheduler software",
        "List of workflow engines",
        "List of rules engines",
        "List of semantic web engines",
        "List of triplestores",
        "List of RDF APIs",
        "List of SPARQL implementations",
        "List of machine learning concepts",
        "List of datasets for machine-learning research",
        "List of datasets for natural language processing",
        "List of computer vision datasets",
        "List of artificial intelligence projects",
        "List of artificial intelligence companies",
        "List of quantum computing companies",
        "List of deep learning software",
        "List of artificial neural network software",
        "List of GPUs",
        "List of NVIDIA graphics processing units",
        "List of AMD graphics processing units",
        "List of ARM processors",
        "List of Intel microprocessors",
        "List of Power ISA processors",
        "List of instruction sets",
        "List of emerging technologies",
        "List of programming tools",
        "List of software engineering topics",
        "List of computer science awards",
        "List of pioneers in computer science",
        "List of computer scientists",
        "List of pioneers in database research",
        "List of computer algebra systems",
        "List of textbooks on classical mechanics",
    ]
    comps = [
        "Comparison of programming languages",
        "Comparison of Java and C++",
        "Comparison of Java and Python",
        "Comparison of C Sharp and Java",
        "Comparison of TypeScript and JavaScript",
        "Comparison of browser engines",
        "Comparison of application virtualization software",
        "Comparison of browser synchronizers",
        "Comparison of TLS implementations",
        "Comparison of SSH clients",
        "Comparison of version-control software",
        "Comparison of database access layers",
        "Comparison of DNS server software",
        "Comparison of operating systems",
        "Comparison of Linux distributions",
        "Comparison of Microsoft Windows versions",
        "Comparison of command shells",
        "Comparison of text editors",
        "Comparison of integrated development environments",
        "Comparison of JavaScript-based web servers",
        "Comparison of web frameworks",
        "Comparison of JavaScript charting frameworks",
        "Comparison of JavaScript-based source code editors",
        "Comparison of continuous integration software",
        "Comparison of configuration management software",
        "Comparison of container orchestration systems",
        "Comparison of network monitoring systems",
        "Comparison of lightweight web servers",
        "Comparison of relational database management systems",
        "Comparison of object–relational mapping software",
        "Comparison of structured storage software",
        "Comparison of NoSQL database management systems",
        "Comparison of OLAP servers",
        "Comparison of business integration software",
        "Comparison of enterprise search software",
        "Comparison of issue-tracking systems",
        "Comparison of project management software",
        "Comparison of documentation generators",
        "Comparison of computer-aided software engineering tools",
        "Comparison of software testing frameworks",
        "Comparison of code coverage tools",
        "Comparison of load testing tools",
        "Comparison of web browsers",
        "Comparison of web servers",
        "Comparison of antivirus software",
        "Comparison of firewall software",
        "Comparison of VPN protocols",
        "Comparison of cryptographic hash algorithms",
        "Comparison of symmetric-key encryption algorithms",
        "Comparison of digital audio editors",
        "Comparison of video codecs",
        "Comparison of machine learning frameworks",
        "Comparison of deep learning software",
        "Comparison of neural network software",
        "Comparison of GPU acceleration libraries",
        "Comparison of numerical-analysis software",
        "Comparison of GIS software",
        "Comparison of ERP software",
        "Comparison of CRM systems",
        "Comparison of office suites",
        "Comparison of spreadsheet software",
        "Comparison of instant messaging clients",
        "Comparison of VoIP software",
        "Comparison of video conferencing software",
        "Comparison of remote desktop software",
        "Comparison of email clients",
        "Comparison of feed aggregators",
        "Comparison of wiki software",
        "Comparison of blog software",
        "Comparison of content management systems",
        "Comparison of e-commerce platforms",
        "Comparison of payment systems",
        "Comparison of blockchain platforms",
        "Comparison of smart contract languages",
        "Comparison of decentralized exchanges",
        "Comparison of proof-of-stake systems",
        "Comparison of programming paradigms",
        "Comparison of memory safety approaches",
        "Comparison of garbage collectors",
        "Comparison of parallel computing paradigms",
        "Comparison of cluster software",
        "Comparison of distributed file systems",
        "Comparison of distributed streaming processing systems",
        "Comparison of stream processing engines",
        "Comparison of batch scheduling systems",
        "Comparison of workflow languages",
        "Comparison of rules engines",
        "Comparison of robotic process automation software",
        "Comparison of low-code development platforms",
        "Comparison of rapid application development tools",
        "Comparison of microservice frameworks",
        "Comparison of service meshes",
        "Comparison of API gateways",
        "Comparison of identity providers",
        "Comparison of single sign-on implementations",
        "Comparison of hardware security modules",
        "Comparison of trusted execution environments",
    ]
    return lists + comps


def _cloud_vendors_and_products() -> list[str]:
    return [
        "Amazon Web Services",
        "Google Cloud",
        "Microsoft Azure",
        "Oracle Cloud",
        "IBM Cloud",
        "Salesforce",
        "Snowflake Inc.",
        "Databricks",
        "Datadog",
        "New Relic",
        "Dynatrace",
        "PagerDuty",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "Azure DevOps",
        "Jenkins (software)",
        "CircleCI",
        "Travis CI",
        "GitHub Actions",
        "Terraform (software)",
        "Pulumi",
        "Crossplane (software)",
        "Ansible (software)",
        "Chef (software)",
        "Puppet (software)",
        "Salt (software)",
        "Vagrant (software)",
        "Packer (software)",
        "Nomad (software)",
        "Harbor (software)",
        "Flux CD",
        "Argo CD",
        "Spinnaker (software)",
        "Tekton (software)",
        "Buildkite",
        "TeamCity",
        "Bamboo (software)",
        "Gradle",
        "Apache Ant",
        "GNU Make",
        "Ninja (build system)",
        "Meson (software)",
        "Bazel (software)",
        "Buck (software)",
        "Pants (software)",
        "Poetry (software)",
        "pip (package manager)",
        "npm (software)",
        "Yarn (package manager)",
        "pnpm",
        "Cargo (Rust)",
        "RubyGems",
        "Composer (software)",
        "NuGet",
        "vcpkg",
        "Conan (software)",
        "Homebrew (package manager)",
        "Chocolatey",
        "APT (software)",
        "DNF (software)",
        "Zypper",
        "Pacman (Arch Linux)",
        "Snap (software)",
        "Flatpak",
        "AppImage",
        "Docker Hub",
        "Amazon Elastic Container Registry",
        "JFrog Artifactory",
        "Sonatype Nexus",
        "PyPI",
        "Anaconda (Python distribution)",
        "Conda (package manager)",
        "MLflow",
        "Weights & Biases",
        "Neptune (software)",
        "TensorBoard",
        "Hugging Face",
        "OpenAI",
        "Anthropic",
        "Cohere",
        "Mistral AI",
        "LangChain",
        "LlamaIndex",
        "Haystack (software)",
        "Semantic Kernel",
        "AutoGPT",
        "Langfuse",
        "Valkey",
        "Dragonfly (software)",
        "KeyDB",
        "ScyllaDB",
        "YugabyteDB",
        "CockroachDB",
        "PlanetScale",
        "Neon (software)",
        "Supabase",
        "Firebase",
        "Appwrite",
        "Parse (platform)",
        "Realm (database)",
        "Couchbase",
        "ArangoDB",
        "OrientDB",
        "JanusGraph",
        "TigerGraph",
        "Dgraph",
        "Memgraph",
        "VictoriaMetrics",
        "Thanos (software)",
        "Mimir (software)",
        "Loki (software)",
        "Cortex (software)",
        "Tempo (software)",
        "Pyroscope (software)",
        "Polar Signals",
        "Netdata",
        "Checkmk",
        "Nagios",
        "Zabbix",
        "Icinga",
        "Sensu (software)",
        "Telegraf (software)",
        "Collectd",
        "StatsD",
        "Graphite (software)",
        "Apache Cassandra",
        "Apache HBase",
        "Apache Accumulo",
        "Apache CouchDB",
        "Apache Pinot",
        "Apache Druid",
        "Apache Iceberg",
        "Apache Hudi",
        "Apache CarbonData",
        "Delta Lake",
        "LakeFS",
        "DVC (software)",
        "Pachyderm (software)",
        "Great Expectations (software)",
        "Monte Carlo Data",
        "Soda SQL",
        "Datafold",
        "dbt (software)",
        "Apache Sedona",
        "GeoMesa",
        "PostGIS",
        "SpatiaLite",
        "GDAL",
        "PROJ",
        "GeoJSON",
        "Shapefile",
        "Well-known text representation of geometry",
        "Web Mercator projection",
        "OGC",
        "GeoTIFF",
        "Cloud Optimized GeoTIFF",
        "STAC (metadata)",
        "ISO 19115",
        "Coordinate reference system",
        "Spatial reference system",
        "Universal Transverse Mercator coordinate system",
        "Geohash",
        "H3 (spatial index)",
        "S2 Geometry",
        "Quadtree",
        "R-tree",
        "K-d tree",
        "Ball tree",
        "Cover tree",
        "Locality-sensitive hashing",
        "Product quantization",
        "Inverted multi-index",
        "Approximate nearest neighbor search",
        "FAISS",
        "Annoy (Approximate Nearest Neighbors Oh Yeah)",
        "ScaNN",
        "Hnswlib",
        "NMSLIB",
        "Voyager (software)",
        "Spotlight (software)",
        "Milvus (vector database)",
        "Weaviate",
        "Qdrant",
        "Pinecone (software)",
        "Chroma (database)",
        "LanceDB",
        "Marqo",
        "Txtai",
        "Sentence embedding",
        "Word2vec",
        "GloVe",
        "FastText",
        "Universal Sentence Encoder",
        "SBERT",
        "CLIP (machine learning model)",
        "OpenCLIP",
        "ViT",
        "ConvNeXt",
        "ResNet",
        "DenseNet",
        "EfficientNet",
        "MobileNet",
        "YOLO (object detection)",
        "R-CNN",
        "Mask R-CNN",
        "RetinaNet",
        "DETR",
        "SAM (Segment Anything Model)",
        "Stable Diffusion",
        "Imagen (text-to-image model)",
        "DALL-E",
        "Midjourney",
        "Flux (text-to-image model)",
        "GAN",
        "Diffusion model",
        "Score-based generative modeling",
        "Variational inference",
        "Normalizing flow",
        "Real NVP",
        "Glow (machine learning)",
        "Invertible neural network",
        "Energy-based model",
        "Hopfield network",
        "Boltzmann machine",
        "Restricted Boltzmann machine",
        "Deep belief network",
        "Self-organizing map",
        "Growing neural gas",
        "Neural Turing machine",
        "Differentiable neural computer",
        "Transformer (deep learning architecture)",
        "BERT (language model)",
        "GPT-4",
        "GPT-3",
        "Large language model",
        "Prompt engineering",
        "Chain-of-thought prompting",
        "Retrieval-augmented generation",
        "Toolformer",
        "ReAct (language model)",
        "Constitutional AI",
        "Reinforcement learning from human feedback",
        "Direct preference optimization",
        "Proximal Policy Optimization",
        "Trust region policy optimization",
        "Actor–critic algorithm",
        "Soft actor–critic",
        "Deep Q-learning",
        "Double Q-learning",
        "Dueling neural networks",
        "Rainbow DQN",
        "Monte Carlo tree search",
        "AlphaGo",
        "AlphaFold",
        "OpenFold",
        "ESMFold",
        "Protein structure prediction",
        "Homology modeling",
        "Molecular dynamics",
        "GROMACS",
        "LAMMPS",
        "NAMD",
        "Amber (software)",
        "Rosetta (software)",
        "Foldit",
        "Cryo-EM",
        "X-ray crystallography",
        "Nuclear magnetic resonance spectroscopy of proteins",
        "Homology (biology)",
        "Sequence alignment",
        "Multiple sequence alignment",
        "Hidden Markov model",
        "Profile hidden Markov model",
        "Position-specific scoring matrices",
        "BLAST (biotechnology)",
        "Smith–Waterman algorithm",
        "Needleman–Wunsch algorithm",
        "FASTA format",
        "FASTQ format",
        "SAM (file format)",
        "BAM file format",
        "Variant Call Format",
        "BED (file format)",
        "GFF",
        "Gene Ontology",
        "Kyoto Encyclopedia of Genes and Genomes",
        "UniProt",
        "Protein Data Bank",
        "PubChem",
        "ChEMBL",
        "DrugBank",
        "HomoloGene",
        "Ensembl",
        "UCSC Genome Browser",
        "GenBank",
        "European Nucleotide Archive",
        "Sequence Read Archive",
        "Burrows–Wheeler transform",
        "FM-index",
        "Minimap2",
        "BWA (algorithm)",
        "STAR (software)",
        "Hisat",
        "Salmon (software)",
        "Kallisto (software)",
        "DESeq2",
        "edgeR",
        "Gene set enrichment analysis",
        "Single-cell RNA sequencing",
        "10x Genomics",
        "Spatial transcriptomics",
        "Mass cytometry",
        "Flow cytometry",
        "Fluorescence in situ hybridization",
        "Chromatin immunoprecipitation sequencing",
        "ATAC-seq",
        "Hi-C (technique)",
        "Epigenomics",
        "DNA methylation",
        "Histone acetylation and deacetylation",
        "Long non-coding RNA",
        "MicroRNA",
        "RNA interference",
        "CRISPR gene editing",
        "Prime editing",
        "Base editing",
        "Homology-directed repair",
        "Non-homologous end joining",
        "Adeno-associated virus",
        "Lentivirus",
        "Retrovirus",
        "Phage therapy",
        "Monoclonal antibody",
        "Bispecific monoclonal antibody",
        "ADC (immunology)",
        "Immune checkpoint inhibitors",
        "CAR T cell",
        "NK cell",
        "Dendritic cell",
        "Major histocompatibility complex",
        "Human leukocyte antigen",
        "Antigen-presenting cell",
        "T-cell receptor",
        "B-cell receptor",
        "Immunoglobulin class switching",
        "V(D)J recombination",
        "Somatic hypermutation",
        "Affinity maturation",
        "Germinal center",
        "Clonal selection",
        "Innate immune system",
        "Adaptive immune system",
        "Complement system",
        "Neutrophil extracellular traps",
        "Cytokine storm",
        "Sepsis",
        "Septic shock",
        "Acute respiratory distress syndrome",
        "Mechanical ventilation",
        "Extracorporeal membrane oxygenation",
        "Hemodialysis",
        "Continuous renal replacement therapy",
        "Plasmapheresis",
        "Stem-cell therapy",
        "Mesenchymal stem cell",
        "Induced pluripotent stem cell",
        "Embryonic stem cell",
        "Organoid",
        "Lab-on-a-chip",
        "Microfluidics",
        "Droplet digital PCR",
        "Quantitative PCR",
        "Reverse transcription polymerase chain reaction",
        "Western blot",
        "ELISA",
        "Mass spectrometry",
        "Liquid chromatography–mass spectrometry",
        "Gas chromatography–mass spectrometry",
        "Nuclear magnetic resonance spectroscopy",
        "Electron microscopy",
        "Cryogenic electron microscopy",
        "Super-resolution microscopy",
        "Fluorescence recovery after photobleaching",
        "Förster resonance energy transfer",
        "Photoactivated localization microscopy",
        "STED microscopy",
        "Structured illumination microscopy",
        "Expansion microscopy",
        "Immunofluorescence",
        "Immunohistochemistry",
        "In situ hybridization",
        "RNAscope",
        "MERFISH",
        "SeqFISH",
        "Spatial biology",
        "Digital pathology",
        "Whole slide imaging",
        "Radiomics",
        "Medical imaging",
        "Picture archiving and communication system",
        "DICOM",
        "HL7",
        "FHIR",
        "OMOP Common Data Model",
        "Observational Medical Outcomes Partnership",
        "Electronic health record",
        "Clinical decision support system",
        "Clinical trial",
        "Randomized controlled trial",
        "Adaptive clinical trial",
        "Clinical trial management system",
        "Good clinical practice",
        "Institutional review board",
        "Patient consent",
        "HIPAA",
        "GDPR",
        "California Consumer Privacy Act",
        "Personally identifiable information",
        "Data anonymization",
        "Pseudonymization",
        "K-anonymity",
        "Differential privacy",
        "Homomorphic encryption",
        "Secure multi-party computation",
        "Zero-knowledge proof",
        "zk-SNARK",
        "zk-STARK",
        "Bulletproofs",
        "Ring signature",
        "Group signature",
        "Blind signature",
        "Threshold cryptography",
        "Shamir's Secret Sharing",
        "Multi-party computation",
        "Garbled circuit",
        "Oblivious transfer",
        "Private information retrieval",
        "Fully homomorphic encryption",
        "Learning with errors",
        "Ring learning with errors",
        "Post-quantum cryptography",
        "CRYSTALS-Kyber",
        "CRYSTALS-Dilithium",
        "SPHINCS+",
        "Classic McEliece",
        "NIST Post-Quantum Cryptography Standardization",
        "Quantum key distribution",
        "BB84 protocol",
        "E91 protocol",
        "Decoy state quantum key distribution",
        "Quantum random number generator",
        "Quantum supremacy",
        "Quantum error correction",
        "Surface code",
        "Stabilizer code",
        "Topological quantum computer",
        "Superconducting quantum computing",
        "Trapped ion quantum computer",
        "Photonic quantum computing",
        "Neutral atom quantum computer",
        "Quantum circuit",
        "Quantum gate",
        "Quantum Fourier transform",
        "Shor's algorithm",
        "Grover's algorithm",
        "Quantum phase estimation algorithm",
        "Variational quantum eigensolver",
        "Quantum approximate optimization algorithm",
        "Quantum machine learning",
        "Quantum neural network",
        "Quantum kernel method",
        "PennyLane (software)",
        "Qiskit",
        "Cirq",
        "Amazon Braket",
        "Azure Quantum",
        "Quantum Inspire",
        "Quantum Computing Stack Exchange",
    ]


def build_mass_additional_topics() -> list[str]:
    parts = (
        _languages_and_runtimes()
        + _frameworks_web()
        + _systems_os_kernel()
        + _languages_more_cs_theory()
        + _list_and_comparison_articles()
        + _cloud_vendors_and_products()
    )
    seen: set[str] = set()
    out: list[str] = []
    for t in parts:
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


MASS_ADDITIONAL_TOPICS = build_mass_additional_topics()
