"""
Prepare clean SFT training data from high-quality Python coding datasets.

Primary source: ise-uiuc/Magicoder-OSS-Instruct-75K
  - 75K Python problems generated by GPT-4 from real open-source code
  - Filtered to syntactically valid Python functions with def + return

Optional secondary: any local JSONL with {problem, solution} or ChatML format

Output format (100% consistent — no mixed think/no-think ambiguity):
  <|im_start|>system
  {SYSTEM}<|im_end|>
  <|im_start|>user
  {problem}<|im_end|>
  <|im_start|>assistant
  ```python
  {solution}
  ```<|im_end|>

Usage:
    # Full run (downloads ~200MB from HF):
    python scripts/prepare_sft_data.py

    # Local smoke test (1000 records, no full download needed):
    python scripts/prepare_sft_data.py --sample 1000 --output data/sft_sample.jsonl
"""

import argparse
import ast
import json
import random
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

SYSTEM_PROMPT = (
    "You are an expert Python programmer. "
    "Write clean, correct, well-structured Python code."
)

# Non-Python code signals — any of these in a solution → reject
_NON_PYTHON_PATTERNS = [
    r"\bfunction\s+\w+\s*\(",   # JavaScript
    r"\bpublic\s+class\b",       # Java/C#
    r"\bpublic\s+static\b",      # Java
    r"<html", r"<div", r"<body", # HTML
    r"\bvar\s+\w+\s*=",          # JavaScript var
    r"\blet\s+\w+\s*=",          # JavaScript let
    r"\bconst\s+\w+\s*=",        # JavaScript const
    r"#include\s*<",             # C/C++
    r"\bfunc\s+\w+\s*\(",        # Go
    r"\bSELECT\b.*\bFROM\b",     # SQL (case-insensitive handled below)
    r"\bpublic\s+\w+\s+\w+\s*\(", # Java method
]
_NON_PYTHON_RE = re.compile("|".join(_NON_PYTHON_PATTERNS), re.IGNORECASE)


def is_valid_python_solution(code: str) -> bool:
    """Return True if code is syntactically valid Python with a function definition."""
    if len(code) < 30 or len(code) > 4000:
        return False
    if "def " not in code:
        return False
    if not ("return" in code or "yield" in code or "pass" in code or "raise" in code):
        return False
    if _NON_PYTHON_RE.search(code):
        return False
    try:
        ast.parse(code)
        return True
    except SyntaxError:
        return False


def extract_longest_python_block(text: str) -> str:
    """Extract the longest ```python ... ``` block from text."""
    blocks = re.findall(r"```python\n(.*?)```", text, re.DOTALL)
    if not blocks:
        # Also try plain ``` blocks
        blocks = re.findall(r"```\n(.*?)```", text, re.DOTALL)
    if not blocks:
        return ""
    return max(blocks, key=len).strip()


def build_chatml(problem: str, solution: str) -> str:
    return (
        f"<|im_start|>system\n{SYSTEM_PROMPT}<|im_end|>\n"
        f"<|im_start|>user\n{problem.strip()}<|im_end|>\n"
        f"<|im_start|>assistant\n"
        f"```python\n{solution.strip()}\n```"
        f"<|im_end|>"
    )


# ── Dataset loaders ───────────────────────────────────────────────────────────

def load_hf_dataset(repo: str, split: str, problem_key: str, solution_key: str,
                    name: str, sample: int | None = None) -> list[dict]:
    """Generic HF dataset loader."""
    try:
        from datasets import load_dataset
    except ImportError:
        print(f"[{name}] ERROR: `pip install datasets` required", flush=True)
        return []

    print(f"[{name}] Loading {repo} ...", flush=True)
    try:
        ds = load_dataset(repo, split=split)
    except Exception as e:
        print(f"[{name}] Load failed: {e}", flush=True)
        return []

    if sample:
        ds = ds.select(range(min(sample * 4, len(ds))))

    records = []
    skipped = {"no_code": 0, "bad_python": 0, "no_def": 0}

    for ex in ds:
        problem = (ex.get(problem_key) or "").strip()
        solution = (ex.get(solution_key) or "").strip()
        if not problem or not solution:
            skipped["no_code"] += 1
            continue
        if "```" in solution:
            code = extract_longest_python_block(solution) or solution
        else:
            code = solution
        if not is_valid_python_solution(code):
            if "def " not in code:
                skipped["no_def"] += 1
            else:
                skipped["bad_python"] += 1
            continue
        records.append({
            "source": name,
            "chatml": build_chatml(problem, code),
            "prompt": problem,
            "test_code": "",
            "language": "python",
        })
        if sample and len(records) >= sample:
            break

    print(f"[{name}] {len(records)} valid records  (skipped: {skipped})", flush=True)
    return records


def load_magicoder(sample: int | None = None) -> list[dict]:
    """Download and filter ise-uiuc/Magicoder-OSS-Instruct-75K."""
    try:
        from datasets import load_dataset
    except ImportError:
        print("[magicoder] ERROR: `pip install datasets` required", flush=True)
        return []

    print("[magicoder] Loading ise-uiuc/Magicoder-OSS-Instruct-75K ...", flush=True)
    ds = load_dataset("ise-uiuc/Magicoder-OSS-Instruct-75K", split="train")
    if sample:
        ds = ds.select(range(min(sample * 3, len(ds))))  # oversample then filter

    records = []
    skipped = {"no_code": 0, "bad_python": 0, "no_def": 0}

    for ex in ds:
        problem = (ex.get("problem") or ex.get("instruction") or "").strip()
        solution = (ex.get("solution") or ex.get("response") or "").strip()

        if not problem or not solution:
            skipped["no_code"] += 1
            continue

        # Solution might be raw code or wrapped in a code fence
        if "```" in solution:
            code = extract_longest_python_block(solution)
            if not code:
                code = solution
        else:
            code = solution

        if not is_valid_python_solution(code):
            if "def " not in code:
                skipped["no_def"] += 1
            else:
                skipped["bad_python"] += 1
            continue

        records.append({
            "source": "magicoder",
            "chatml": build_chatml(problem, code),
            "prompt": problem,
            "test_code": "",
            "language": "python",
        })

        if sample and len(records) >= sample:
            break

    print(f"[magicoder] {len(records)} valid records  (skipped: {skipped})", flush=True)
    return records


def load_local_jsonl(path: Path) -> list[dict]:
    """Load a local JSONL with {problem, solution} or existing ChatML records."""
    records = []
    skipped = 0
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)

            # Already formatted ChatML
            if "chatml" in rec and "<|im_start|>assistant" in rec.get("chatml", ""):
                chatml = rec["chatml"]
                idx = chatml.rfind("<|im_start|>assistant\n")
                asst = chatml[idx + len("<|im_start|>assistant\n"):]
                code = extract_longest_python_block(asst)
                if not code:
                    code = asst.replace("<|im_end|>", "").strip()
                if not is_valid_python_solution(code):
                    skipped += 1
                    continue
                # Re-format with current system prompt for consistency
                problem = rec.get("prompt", "")
                records.append({
                    "source": rec.get("source", path.stem),
                    "chatml": build_chatml(problem, code) if problem else chatml,
                    "prompt": problem,
                    "test_code": rec.get("test_code", ""),
                    "language": "python",
                })
                continue

            # Raw problem/solution pairs
            problem = (rec.get("problem") or rec.get("prompt") or rec.get("instruction") or "").strip()
            solution = (rec.get("solution") or rec.get("code") or rec.get("response") or "").strip()
            if not problem or not solution:
                skipped += 1
                continue
            if "```" in solution:
                solution = extract_longest_python_block(solution) or solution
            if not is_valid_python_solution(solution):
                skipped += 1
                continue
            records.append({
                "source": path.stem,
                "chatml": build_chatml(problem, solution),
                "prompt": problem,
                "test_code": rec.get("test_code", ""),
                "language": "python",
            })

    print(f"[{path.stem}] {len(records)} valid records  (skipped: {skipped})", flush=True)
    return records


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="data/sft_clean.jsonl")
    parser.add_argument("--sample", type=int, default=None,
                        help="Limit to N records per source (for local smoke testing)")
    parser.add_argument("--extra", nargs="*", default=[],
                        help="Additional local JSONL files to include")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)
    all_records: list[dict] = []

    # Primary: Magicoder-OSS-Instruct-75K (~25K valid Python after filtering)
    all_records.extend(load_magicoder(sample=args.sample))

    # Secondary: CodeFeedback-Filtered-Instruction (~20K additional valid Python)
    all_records.extend(load_hf_dataset(
        repo="m-a-p/CodeFeedback-Filtered-Instruction",
        split="train",
        problem_key="query",
        solution_key="answer",
        name="codefeedback",
        sample=args.sample,
    ))

    # Optional extra local files
    for extra in args.extra:
        p = Path(extra)
        if p.exists():
            all_records.extend(load_local_jsonl(p))
        else:
            print(f"[extra] WARNING: {p} not found — skipping", flush=True)

    if not all_records:
        print("ERROR: No records produced. Check dataset availability.", flush=True)
        sys.exit(1)

    random.shuffle(all_records)

    out_path = Path(args.output)
    if not out_path.is_absolute():
        out_path = Path(__file__).parent.parent / args.output
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with open(out_path, "w") as f:
        for rec in all_records:
            f.write(json.dumps(rec) + "\n")

    # Audit
    total = len(all_records)
    has_def    = sum(1 for r in all_records if "def "    in r.get("chatml", ""))
    has_return = sum(1 for r in all_records if "return"  in r.get("chatml", ""))
    has_test   = sum(1 for r in all_records if r.get("test_code"))
    has_fence  = sum(1 for r in all_records if "```python" in r.get("chatml", ""))

    print(f"\n[DONE] {total} records → {out_path}")
    print(f"[AUDIT] has def:          {has_def}   ({100*has_def/max(total,1):.1f}%)")
    print(f"[AUDIT] has return:       {has_return}   ({100*has_return/max(total,1):.1f}%)")
    print(f"[AUDIT] has ```python:    {has_fence}   ({100*has_fence/max(total,1):.1f}%)")
    print(f"[AUDIT] has test_code:    {has_test}   ({100*has_test/max(total,1):.1f}%)")

    # Spot-check 3 random examples
    print("\n[SPOT CHECK] 3 random examples:")
    for rec in random.sample(all_records, min(3, len(all_records))):
        chatml = rec["chatml"]
        idx = chatml.rfind("<|im_start|>assistant\n")
        asst = chatml[idx + len("<|im_start|>assistant\n"):][:200]
        print(f"  source={rec['source']}  asst_start={repr(asst[:80])}")


if __name__ == "__main__":
    main()
