#!/usr/bin/env bash
# SFT on clean coding data.
# Trains student to produce <think>...</think> + code.
#
# Data priority:
#   1. data/qwen_sft_solutions.jsonl  (coding problems, generated by Qwen)
#   2. data/claude_opus_traces.jsonl + data/hermes_traces.jsonl (clean general Q&A)
#
# Run `python scripts/prepare_sft_data.py` first to build data/sft_clean.jsonl.

set -e
cd "$(dirname "$0")/.."
source .venv/bin/activate

mkdir -p logs checkpoints/sft

LOG="logs/sft_reasoning_$(date +%Y%m%d_%H%M%S).log"
echo "=== CodingSSM SFT ===" | tee "$LOG"
echo "Log: $LOG" | tee -a "$LOG"

# Step 1: Prepare clean SFT data
echo "[STEP 1] Preparing clean SFT data..." | tee -a "$LOG"
python -u scripts/prepare_sft_data.py \
  --qwen-solutions data/qwen_sft_solutions.jsonl \
  --output data/sft_clean.jsonl \
  2>&1 | tee -a "$LOG"

NLINES=$(wc -l < data/sft_clean.jsonl)
echo "[INFO] SFT dataset: $NLINES records" | tee -a "$LOG"

# Step 2: Smoke test (fast sanity check before full training run)
echo "[STEP 2] Running smoke test..." | tee -a "$LOG"
python -u -m train.smoke_test_sft 2>&1 | tee -a "$LOG"

echo "[INFO] Smoke test passed. Starting SFT training..." | tee -a "$LOG"

# Step 3: Full SFT
# H100 80GB: batch 4 × accum 8 = effective 32; seq_len 2048 with grad checkpoint
python -u -m train.sft_reasoning \
  --traces data/sft_clean.jsonl \
  --output-dir checkpoints/sft \
  --model-size 700m \
  --epochs 3 \
  --lr 3e-4 \
  --batch-size 4 \
  --grad-accum 8 \
  --max-seq-len 2048 \
  --save-every 200 \
  2>&1 | tee -a "$LOG"
